ElevenNoteWeb/Controllers/NotesController.cs
using Contracts;
using ElevenNoteWeb.Models;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElevenNoteWeb.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {

        private DataManagement _data = new DataManagement();

        /// <summary>
        /// Gets the ID of the current user.
        /// </summary>
        /// <returns></returns>
        private Guid GetUserId()
        {
            using (var c = new ApplicationDbContext())
            {
                var userId = c.Users.Where(w => w.UserName == User.Identity.Name).Select(s => s.Id).FirstOrDefault();

                //var id = (
                //    from user in c.Users 
                //    where user.UserName == User.Identity.Name 
                //    select user.Id).FirstOrDefault();

                return new Guid(userId);
            }
        }

        // GET: Notes
        public ActionResult Index()
        {
            var notes = _data.GetAll(GetUserId());
            return View(notes);
        }

        [HttpGet]
        [ActionName("Create")]
        public ActionResult CreateGet()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [ActionName("Create")]
        public ActionResult CreatePost(NoteDetailViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.UserID = GetUserId().ToString();
                _data.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult EditGet(int? id)
        {
            if (id == null) return HttpNotFound(); // make sure they passed an ID
            var model = _data.GetById(id.Value, GetUserId()); // get the note that matches the ID
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        [ActionName("Edit")]
        public ActionResult EditPost(NoteDetailViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.UserID = GetUserId().ToString();
                _data.Update(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteGet(int? id)
        {
            if (id == null) return HttpNotFound(); // make sure they passed an ID
            var model = _data.GetById(id.Value, GetUserId()); // get the note that matches the ID
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            // Attempt to retrieve the Note so they can preview before deleting.
            var model = _data.GetById(id.Value, GetUserId());
            if (model != null)
            {
                _data.Delete(id.Value, GetUserId());
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound(); // returns a 404
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null) return HttpNotFound(); // make sure they passed an ID
            var model = _data.GetById(id.Value, GetUserId()); // get the note that matches the ID
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }
    }
}

ElevenNoteWeb/Views/Shared/_Layout.cshtml
@using System.Configuration
@{
    var _appName = ConfigurationManager.AppSettings["ApplicationName"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @_appName</title>

    <script src="@Url.Content("~/Scripts/ckeditor/ckeditor.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/ckeditor/config.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Scripts/ckeditor/contents.css")" type="text/css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/">
                    <img src="@Url.Content("~/Content/elevenfifty-logo.png")" accesskey="" alt="ElevenFifty Logo" />
                </a> @Html.ActionLink(_appName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Notes", "Index", "Notes")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @_appName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>